name: runProspector
channels:
   - defaults
dependencies:
   # Core requirements
   - python=3.11
   - pip
   # Other packages
   - pandas
   - numpy
   - scipy
   - matplotlib
   - astropy
   # pip install
   - pip:
     - emcee
     - dynesty
     - astro-sedpy
     - corner
     - astro-prospector
     - fsps